export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const RESET_USER_ERROR = "RESET_USER_ERROR";
export const RESET_USER_SUCCESS = "RESET_USER_SUCCESS";

export const GET_ALL_BLOG_POSTS_BEGIN = "GET_ALL_BLOG_POSTS_BEGIN";
export const GET_ALL_BLOG_POSTS_SUCCESS = "GET_ALL_BLOG_POSTS_SUCCESS";
export const GET_ALL_BLOG_POSTS_ERROR = "GET_ALL_BLOG_POSTS_ERROR";
