export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const RESET_BLOG_POST = "RESET_BLOG_POST";
export const RESET_USER_ERROR = "RESET_USER_ERROR";
export const RESET_USER_SUCCESS = "RESET_USER_SUCCESS";

export const GET_ALL_BLOG_POSTS_BEGIN = "GET_ALL_BLOG_POSTS_BEGIN";
export const GET_ALL_BLOG_POSTS_SUCCESS = "GET_ALL_BLOG_POSTS_SUCCESS";
export const GET_ALL_BLOG_POSTS_ERROR = "GET_ALL_BLOG_POSTS_ERROR";

export const GET_SINGLE_BLOG_POST_BEGIN = "GET_SINGLE_BLOG_POST";
export const GET_SINGLE_BLOG_POST_SUCCESS = "GET_SINGLE_BLOG_POST_SUCCESS";
export const GET_SINGLE_BLOG_POST_ERROR = "GET_SINGLE_BLOG_POST_ERROR";

export const ADD_BLOG_POST_BEGIN = "ADD_BLOG_POST_BEGIN";
export const ADD_BLOG_POST_SUCCESS = "ADD_BLOG_POST_SUCCESS";
export const ADD_BLOG_POST_ERROR = "ADD_BLOG_POST_ERROR";

export const EDIT_BLOG_POST_BEGIN = "EDIT_BLOG_POST_BEGIN";
export const EDIT_BLOG_POST_SUCCESS = "EDIT_BLOG_POST_SUCCESS";
export const EDIT_BLOG_POST_ERROR = "EDIT_BLOG_POST_ERROR";

export const DELETE_BLOG_POST_BEGIN = "DELETE_BLOG_POST_BEGIN";
export const DELETE_BLOG_POST_SUCCESS = "DELETE_BLOG_POST_SUCCESS";
export const DELETE_BLOG_POST_ERROR = "DELETE_BLOG_POST_ERROR";

export const GET_ALL_COMMENTS_BLOG_POST_BEGIN =
  "GET_ALL_COMMENTS_BLOG_POST_BEGIN";
export const GET_ALL_COMMENTS_BLOG_POST_SUCCESS =
  "GET_ALL_COMMENTS_BLOG_POST_SUCCESS";
export const GET_ALL_COMMENTS_BLOG_POST_ERROR =
  "GET_ALL_COMMENTS_BLOG_POST_ERROR";

export const GET_ALL_COMMENTS_USER_BEGIN = "GET_ALL_COMMENTS_USER_BEGIN";
export const GET_ALL_COMMENTS_USER_SUCCESS = "GET_ALL_COMMENTS_USER_SUCCESS";
export const GET_ALL_COMMENTS_USER_ERROR = "GET_ALL_COMMENTS_USER_ERROR";

export const GET_ALL_COMMENTS_BEGIN = "GET_ALL_COMMENTS_BEGIN";
export const GET_ALL_COMMENTS_SUCCESS = "GET_ALL_COMMENTS_SUCCESS";
export const GET_ALL_COMMENTS_ERROR = "GET_ALL_COMMENTS_ERROR";

export const ADD_COMMENT_BLOG_POST_BEGIN = "ADD_COMMENT_BLOG_POST_BEGIN";
export const ADD_COMMENT_BLOG_POST_SUCCESS = "ADD_COMMENT_BLOG_POST_SUCCESS";
export const ADD_COMMENT_BLOG_POST_ERROR = "ADD_COMMENT_BLOG_POST_ERROR";

export const EDIT_COMMENT_BLOG_POST_BEGIN = "EDIT_COMMENT_BLOG_POST_BEGIN";
export const EDIT_COMMENT_BLOG_POST_SUCCESS = "EDIT_COMMENT_BLOG_POST_SUCCESS";
export const EDIT_COMMENT_BLOG_POST_ERROR = "EDIT_COMMENT_BLOG_POST_ERROR";

export const DELETE_COMMENT_BLOG_POST_BEGIN = "DELETE_COMMENT_BLOG_POST_BEGIN";
export const DELETE_COMMENT_BLOG_POST_SUCCESS =
  "DELETE_COMMENT_BLOG_POST_SUCCESS";
export const DELETE_COMMENT_BLOG_POST_ERROR = "DELETE_COMMENT_BLOG_POST_ERROR";

export const RESET_COMMENT_ERROR = "RESET_COMMENT_ERROR";

export const DELETE_ALL_COMMENTS_BLOG_POST_BEGIN =
  "DELETE_ALL_COMMENTS_BLOG_POST_BEGIN";
export const DELETE_ALL_COMMENTS_BLOG_POST_SUCCESS =
  "DELETE_ALL_COMMENTS_BLOG_POST_SUCCESS";
export const DELETE_ALL_COMMENTS_BLOG_POST_ERROR =
  "DELETE_ALL_COMMENTS_BLOG_POST_ERROR";
